### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by xuyinan2** [zhangylch/FIREANN#4]
Dear FIREANN Team, 

I encounter an issue when I am using a "PES.pt" file trained based on a reasonably large cutoff (I used 6.0e0). When I am testing the PES.pt file using ASE, the code does not run and gives me a "Segmentation fault (core dumped)".
When I trained the potential based on the same train and validation set and other settings, except for a smaller cutoff (5.0eo in input_density), I could run the ASE code and use the resulting file "PES.pt" with no issues. 

Could it be related to some issues in the fireann code itself? Thank you in advance.

YX

**Comment by zhangylch** [comment]
> Dear FIREANN Team,
> 
> I encounter an issue when I am using a "PES.pt" file trained based on a reasonably large cutoff (I used 6.0e0). When I am testing the PES.pt file using ASE, the code does not run and gives me a "Segmentation fault (core dumped)". When I trained the potential based on the same train and validation set and other settings, except for a smaller cutoff (5.0eo in input_density), I could run the ASE code and use the resulting file "PES.pt" with no issues.
> 
> Could it be related to some issues in the fireann code itself? Thank you in advance.
> 
> YX
Sorry for the late reply. Can you upload a screenshot of the error? I think it might have something to do with the maxneigh setting. What is your maxneigh setting?

**Comment by xuyinan2** [comment]
Dear zhangylch,

Thank you for the suggestion. For a PES.py generated based on a higher cutoff, I increased maxneigh in the original ASE code (doubled), and now there is no segmentation fault. 
Thank you. It might be helpful if a note can be added next to the "maxneigh" entry.

YX

**Comment by zhangylch** [comment]
> Dear zhangylch,
> 
> Thank you for the suggestion. For a PES.py generated based on a higher cutoff, I increased maxneigh in the original ASE code (doubled), and now there is no segmentation fault. Thank you. It might be helpful if a note can be added next to the "maxneigh" entry.
> 
> YX

Thank you for your suggestion! We will add it in next push.
