### ISSUE TITLE
Can FIREANN run smoothly with versions 1.13.1 of PyTorch?

### ISSUE THREAD

**Issue by MD-NNP** [zhangylch/FIREANN#5]
Hi，yaolong
Due to the cluster's CUDA version being 11.6 and constraints on upgrading due to limited public resources, it's not possible to install PyTorch version 2.0 (which requires CUDA 11.7 or higher). Can FIREANN run smoothly with PyTorch version 1.13.1?
Thank you for patiently answering my questions!

**Comment by zhangylch** [comment]
> Hi，yaolong Due to the cluster's CUDA version being 11.6 and constraints on upgrading due to limited public resources, it's not possible to install PyTorch version 2.0 (which requires CUDA 11.7 or higher). Can FIREANN run smoothly with PyTorch version 1.13.1? Thank you for patiently answering my questions!

I believe it can run on pytorch 1.13. My earlier tests were based on pt1.13. If not, feel free to contact me, I think it's easy to fix.

**Comment by MD-NNP** [comment]
Thank you, I'll give it a shot later.

**Comment by MD-NNP** [comment]
> > Hi，yaolong Due to the cluster's CUDA version being 11.6 and constraints on upgrading due to limited public resources, it's not possible to install PyTorch version 2.0 (which requires CUDA 11.7 or higher). Can FIREANN run smoothly with PyTorch version 1.13.1? Thank you for patiently answering my questions!
> 
> I believe it can run on pytorch 1.13. My earlier tests were based on pt1.13. If not, feel free to contact me, I think it's easy to fix.

**Comment by MD-NNP** [comment]
After installing the two packages (PyTorch and opt_einsum), I want to run the FIREANNP to train examples, but I couldn't find the path in the manual. Is it supposed to be xx/FIREANNP/run/ ?

**Comment by zhangylch** [comment]
> After installing the two packages (PyTorch and opt_einsum), I want to run the FIREANNP to train examples, but I couldn't find the path in the manual. Is it supposed to be xx/FIREANNP/run/ ?

You can run the training by "python3 $path "train" ". "path " is the path where you place the codes.

**Comment by MD-NNP** [comment]
> > After installing the two packages (PyTorch and opt_einsum), I want to run the FIREANNP to train examples, but I couldn't find the path in the manual. Is it supposed to be xx/FIREANNP/run/ ?
> 
> You can run the training by "python3 $path "train" ". "path " is the path where you place the codes.

Here is my assignment submission file and the error message encountered when I attempted to train the example as per your instructions.
![1709130926631](https://github.com/zhangylch/FIREANN/assets/114153373/a18fa4d9-07b2-49c2-a1ea-1860b6df100b)
![1709130971085](https://github.com/zhangylch/FIREANN/assets/114153373/4b7e7b21-6830-4676-a40b-8b84e622ff04)

**Comment by zhangylch** [comment]
> > > After installing the two packages (PyTorch and opt_einsum), I want to run the FIREANNP to train examples, but I couldn't find the path in the manual. Is it supposed to be xx/FIREANNP/run/ ?
> > 
> > 
> > You can run the training by "python3 $path "train" ". "path " is the path where you place the codes.
> 
> Here is my assignment submission file and the error message encountered when I attempted to train the example as per your instructions. ![1709130926631](https://private-user-images.githubusercontent.com/114153373/308586992-a18fa4d9-07b2-49c2-a1ea-1860b6df100b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5MTMyODksIm5iZiI6MTcxMDkxMjk4OSwicGF0aCI6Ii8xMTQxNTMzNzMvMzA4NTg2OTkyLWExOGZhNGQ5LTA3YjItNDljMi1hMWVhLTE4NjBiNmRmMTAwYi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMFQwNTM2MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMTY0MjE2OWNkNDAxMmE5NGZhMzUxY2I2ZTg5MjdkMmZjZTY0OWJmM2JhNGZlZGQzYzE4ZTRjMGQwOTk5NGQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8INeaaC_ToD2AJSRyxIcCUf2-swLgCcKaMIAuEVJPwM) ![1709130971085](https://private-user-images.githubusercontent.com/114153373/308587217-4b7e7b21-6830-4676-a40b-8b84e622ff04.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5MTMyODksIm5iZiI6MTcxMDkxMjk4OSwicGF0aCI6Ii8xMTQxNTMzNzMvMzA4NTg3MjE3LTRiN2U3YjIxLTY4MzAtNDY3Ni1hNDBiLThiODRlNjIyZmYwNC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMFQwNTM2MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NzkzOWFiZTljZGZiMjZmNzFjMzhiYjAxOTZhNmMyOTI1ODg1NjY0MDVmNzg0YTJkMDdkOTAyZTQyZWZlM2RiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.T0Bx6CTqalBrmjWShFhdteYgB1prOC2hxVj_mjgD4lM)

Sorry for late reply. There is an example showing how to submit the job in the example/liquid-h2o. It should be like "python3 -m torch.distributed.run --nproc_per_node=$NPROC_PER_NODE --max_restarts=0 --nnodes=$PBS_NUM_NODES --rdzv_id=$PBS_JOBID --rdzv_backend=c10d --rdzv_endpoint=$MASTER:12563 $COMMAND > out". It will lanuch DDP training.

**Comment by MD-NNP** [comment]
> > > > After installing the two packages (PyTorch and opt_einsum), I want to run the FIREANNP to train examples, but I couldn't find the path in the manual. Is it supposed to be xx/FIREANNP/run/ ?
> > > 
> > > 
> > > You can run the training by "python3 $path "train" ". "path " is the path where you place the codes.
> > 
> > 
> > Here is my assignment submission file and the error message encountered when I attempted to train the example as per your instructions. ![1709130926631](https://private-user-images.githubusercontent.com/114153373/308586992-a18fa4d9-07b2-49c2-a1ea-1860b6df100b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5MTMyODksIm5iZiI6MTcxMDkxMjk4OSwicGF0aCI6Ii8xMTQxNTMzNzMvMzA4NTg2OTkyLWExOGZhNGQ5LTA3YjItNDljMi1hMWVhLTE4NjBiNmRmMTAwYi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMFQwNTM2MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMTY0MjE2OWNkNDAxMmE5NGZhMzUxY2I2ZTg5MjdkMmZjZTY0OWJmM2JhNGZlZGQzYzE4ZTRjMGQwOTk5NGQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8INeaaC_ToD2AJSRyxIcCUf2-swLgCcKaMIAuEVJPwM) ![1709130971085](https://private-user-images.githubusercontent.com/114153373/308587217-4b7e7b21-6830-4676-a40b-8b84e622ff04.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5MTMyODksIm5iZiI6MTcxMDkxMjk4OSwicGF0aCI6Ii8xMTQxNTMzNzMvMzA4NTg3MjE3LTRiN2U3YjIxLTY4MzAtNDY3Ni1hNDBiLThiODRlNjIyZmYwNC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMFQwNTM2MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NzkzOWFiZTljZGZiMjZmNzFjMzhiYjAxOTZhNmMyOTI1ODg1NjY0MDVmNzg0YTJkMDdkOTAyZTQyZWZlM2RiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.T0Bx6CTqalBrmjWShFhdteYgB1prOC2hxVj_mjgD4lM)
> 
> Sorry for late reply. There is an example showing how to submit the job in the example/liquid-h2o. It should be like "python3 -m torch.distributed.run --nproc_per_node=$NPROC_PER_NODE --max_restarts=0 --nnodes=$PBS_NUM_NODES --rdzv_id=$PBS_JOBID --rdzv_backend=c10d --rdzv_endpoint=$MASTER:12563 $COMMAND > out". It will lanuch DDP training.

Thanks for your response. I made modifications to the command and submitted the calculation, but encountered the following error. What could be the cause?
![1710997828152](https://github.com/zhangylch/FIREANN/assets/114153373/d97174fa-252b-4187-9251-f55f90ae62f7)
![1710997893876](https://github.com/zhangylch/FIREANN/assets/114153373/1efa6437-99c2-4c18-a9f6-276fd2a36e81)

**Comment by zhangylch** [comment]
> > > > > After installing the two packages (PyTorch and opt_einsum), I want to run the FIREANNP to train examples, but I couldn't find the path in the manual. Is it supposed to be xx/FIREANNP/run/ ?
> > > > 
> > > > 
> > > > You can run the training by "python3 $path "train" ". "path " is the path where you place the codes.
> > > 
> > > 
> > > Here is my assignment submission file and the error message encountered when I attempted to train the example as per your instructions. ![1709130926631](https://private-user-images.githubusercontent.com/114153373/308586992-a18fa4d9-07b2-49c2-a1ea-1860b6df100b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5MTMyODksIm5iZiI6MTcxMDkxMjk4OSwicGF0aCI6Ii8xMTQxNTMzNzMvMzA4NTg2OTkyLWExOGZhNGQ5LTA3YjItNDljMi1hMWVhLTE4NjBiNmRmMTAwYi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMFQwNTM2MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMTY0MjE2OWNkNDAxMmE5NGZhMzUxY2I2ZTg5MjdkMmZjZTY0OWJmM2JhNGZlZGQzYzE4ZTRjMGQwOTk5NGQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8INeaaC_ToD2AJSRyxIcCUf2-swLgCcKaMIAuEVJPwM) ![1709130971085](https://private-user-images.githubusercontent.com/114153373/308587217-4b7e7b21-6830-4676-a40b-8b84e622ff04.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5MTMyODksIm5iZiI6MTcxMDkxMjk4OSwicGF0aCI6Ii8xMTQxNTMzNzMvMzA4NTg3MjE3LTRiN2U3YjIxLTY4MzAtNDY3Ni1hNDBiLThiODRlNjIyZmYwNC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMFQwNTM2MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NzkzOWFiZTljZGZiMjZmNzFjMzhiYjAxOTZhNmMyOTI1ODg1NjY0MDVmNzg0YTJkMDdkOTAyZTQyZWZlM2RiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.T0Bx6CTqalBrmjWShFhdteYgB1prOC2hxVj_mjgD4lM)
> > 
> > 
> > Sorry for late reply. There is an example showing how to submit the job in the example/liquid-h2o. It should be like "python3 -m torch.distributed.run --nproc_per_node=$NPROC_PER_NODE --max_restarts=0 --nnodes=$PBS_NUM_NODES --rdzv_id=$PBS_JOBID --rdzv_backend=c10d --rdzv_endpoint=$MASTER:12563 $COMMAND > out". It will lanuch DDP training.
> 
> Thanks for your response. I made modifications to the command and submitted the calculation, but encountered the following error. What could be the cause? ![1710997828152](https://private-user-images.githubusercontent.com/114153373/315047628-d97174fa-252b-4187-9251-f55f90ae62f7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5OTg0MDQsIm5iZiI6MTcxMDk5ODEwNCwicGF0aCI6Ii8xMTQxNTMzNzMvMzE1MDQ3NjI4LWQ5NzE3NGZhLTI1MmItNDE4Ny05MjUxLWY1NWY5MGFlNjJmNy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMVQwNTE1MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYmIzZjBmNTI0YzhlMDJjMWVkNDFkMDg0YWVhMmY1MmNhZTk4YWY5OTRmNmYwYWIwNjJkMzQyODBmMzkzMjU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nz3dUs4PhQcKgONOIVD0yrDgT1FFAol1jsyguz8OVVQ) ![1710997893876](https://private-user-images.githubusercontent.com/114153373/315048127-1efa6437-99c2-4c18-a9f6-276fd2a36e81.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5OTg0MDQsIm5iZiI6MTcxMDk5ODEwNCwicGF0aCI6Ii8xMTQxNTMzNzMvMzE1MDQ4MTI3LTFlZmE2NDM3LTk5YzItNGMxOC1hOWY2LTI3NmZkMmEzNmU4MS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMVQwNTE1MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZmM0NjFiNTA2NzgzODMxZmQ3ZDZhYzJkYjgzMTJhYTM5YTNhNzA1MzNkMTQwZWM4NWY1YjY4ZTMzMjk5ZjYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fWZ2xgjhMPFPewDlF4Cmm7uU4qbs62aKCiEDOVFdWYo)

Can you show me the entire error message?

**Comment by MD-NNP** [comment]
> 
> Can you show me the entire error message?
Sorry for not providing the complete information. Here is the full error message：
![1711001092404](https://github.com/zhangylch/FIREANN/assets/114153373/6e59d755-6174-4fb3-bd3d-5035f8229b3f)

**Comment by zhangylch** [comment]
> > Can you show me the entire error message?
> > Sorry for not providing the complete information. Here is the full error message：
> > ![1711001092404](https://private-user-images.githubusercontent.com/114153373/315061912-6e59d755-6174-4fb3-bd3d-5035f8229b3f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMDE4MzUsIm5iZiI6MTcxMTAwMTUzNSwicGF0aCI6Ii8xMTQxNTMzNzMvMzE1MDYxOTEyLTZlNTlkNzU1LTYxNzQtNGZiMy1iZDNkLTUwMzVmODIyOWIzZi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMVQwNjEyMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZGJiMTk2MTZkNjQ4MmIzNTRhNGYxYzc4ZWE1MjYyYjE5N2FhNTdmNTFlYTAwY2Y4ZmQyNjE2Y2JkM2M4NDc3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pucy7D1cs8h0fVWB-zmrUOATqimC_5bTzF1IMvfNhSE)

Nothing after the Abort (core dumped)?

**Comment by MD-NNP** [comment]
> > > Can you show me the entire error message?
> > > Sorry for not providing the complete information. Here is the full error message：
> > > ![1711001092404](https://private-user-images.githubusercontent.com/114153373/315061912-6e59d755-6174-4fb3-bd3d-5035f8229b3f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMDE4MzUsIm5iZiI6MTcxMTAwMTUzNSwicGF0aCI6Ii8xMTQxNTMzNzMvMzE1MDYxOTEyLTZlNTlkNzU1LTYxNzQtNGZiMy1iZDNkLTUwMzVmODIyOWIzZi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMVQwNjEyMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZGJiMTk2MTZkNjQ4MmIzNTRhNGYxYzc4ZWE1MjYyYjE5N2FhNTdmNTFlYTAwY2Y4ZmQyNjE2Y2JkM2M4NDc3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pucy7D1cs8h0fVWB-zmrUOATqimC_5bTzF1IMvfNhSE)
> 
> Nothing after the Abort (core dumped)?

Yes, the task was killed after the error occurred, and no additional information was provided.

**Comment by zhangylch** [comment]
> > > > Can you show me the entire error message?
> > > > Sorry for not providing the complete information. Here is the full error message：
> > > > ![1711001092404](https://private-user-images.githubusercontent.com/114153373/315061912-6e59d755-6174-4fb3-bd3d-5035f8229b3f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMDE4MzUsIm5iZiI6MTcxMTAwMTUzNSwicGF0aCI6Ii8xMTQxNTMzNzMvMzE1MDYxOTEyLTZlNTlkNzU1LTYxNzQtNGZiMy1iZDNkLTUwMzVmODIyOWIzZi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMVQwNjEyMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZGJiMTk2MTZkNjQ4MmIzNTRhNGYxYzc4ZWE1MjYyYjE5N2FhNTdmNTFlYTAwY2Y4ZmQyNjE2Y2JkM2M4NDc3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pucy7D1cs8h0fVWB-zmrUOATqimC_5bTzF1IMvfNhSE)
> > 
> > 
> > Nothing after the Abort (core dumped)?
> 
> Yes, the task was killed after the error occurred, and no additional information was provided.

That is wired. Can you try this directive "python3 -m torch.distributed.run --nproc_per_node=1 --max_restarts=0 --nnodes=1 --standalone $path > out"?

**Comment by MD-NNP** [comment]
> 
> That is wired. Can you try this directive "python3 -m torch.distributed.run --nproc_per_node=1 --max_restarts=0 --nnodes=1 --standalone $path > out"?

Thank you for your advice. When I made the modifications and submitted it again, a new error emerged. I attempted to address it, but unfortunately, I failed.
![1711247353683](https://github.com/zhangylch/FIREANN/assets/114153373/8ec56e75-1899-4eb2-85a1-89f40b9f8cad)

**Comment by zhangylch** [comment]
Do you set the table_init to 1 in para/input_nn? The error indicate that the code try to load the trained saved model "REANN.pth"?

**Comment by MD-NNP** [comment]
> Do you set the table_init to 1 in para/input_nn? The error indicate that the code try to load the trained saved model "REANN.pth"?

Thank you for your help! Following your advice, I reviewed the file and made the necessary modifications. Now, I can train the examples without any issues.

**Comment by zhangylch** [comment]
You are welcome!

**Comment by zhangylch** [comment]
> > Do you set the table_init to 1 in para/input_nn? The error indicate that the code try to load the trained saved model "REANN.pth"?
> 
> Thank you for your help! Following your advice, I reviewed the file and made the necessary modifications. Now, I can train the examples without any issues.

Glad to hear that!
