### ISSUE TITLE
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

### ISSUE THREAD

**Issue by GunjanaYadav** [zhangylch/FIREANN#6]
Hi, 
I have successfully executed the training process using the following command: "python3 -m torch.distributed.run --nproc_per_node=$NPROC_PER_NODE --nnodes=1 --standalone $path" 

This was done for the NMA example as outlined in your package manual. The setup utilized PyTorch version 2.0.0, CUDA version 11.7, Opt_einsum version 3.2.0, and cuDNN version 8.5.0.

However, upon installing LAMMPS (version: 10 Feb 2021) with Libtorch (PyTorch version 2.0.0, CUDA version 11.7, Opt_einsum version 3.2.0, and cuDNN version 8.5.0), I encountered an error when running the command:  "mpirun -n 1 ./lmp_mpi -in in.nma >out"
  
The error message received was:

#################################################################################################
LAMMPS (10 Feb 2021)
  using 1 OpenMP thread(s) per MPI task
Reading data file ...
  orthogonal box = (-100.00000 -100.00000 -100.00000) to (100.00000 100.00000 100.00000)
  1 by 1 by 1 MPI processor grid
  reading atoms ...
  12 atoms
  read_data CPU = 0.001 seconds
Replicating atoms ...
  orthogonal box = (-100.00000 -100.00000 -100.00000) to (100.00000 100.00000 100.00000)
  1 by 1 by 1 MPI processor grid
  12 atoms
  replicate CPU = 0.001 seconds
The simulations are performed on the GPU
Load model correctly
Neighbor list info ...
  update every 1 steps, delay 10 steps, check yes
  max neighbors/atom: 2000, page size: 100000
  master list distance cutoff = 5.5
  ghost atom cutoff = 5.5
  1 neighbor lists, perpetual/occasional/extra = 1 0 0
  (1) pair fireann, perpetual
      attributes: full, newton on
      pair build: full/nsq
      stencil: none
      bin: none
Setting up Verlet run ...
  Unit style    : metal
  Current step  : 0
  Time step     : 0.01
terminate called after throwing an instance of 'std::runtime_error'
  what():  The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__/lammps_REANN/density.py", line 63, in forward
    _11 = torch.__range_length(1, int(nipsin), 1)
    for _12 in range(_11):
      _13 = torch.einsum("ji,ki -> jki", [angular[-1], dist_vec1])
            ~~~~~~~~~~~~ <--- HERE
      _14 = torch.reshape(_13, [-1, totneighbour])
      _15 = torch.append(angular, _14)

Traceback of TorchScript, original code (most recent call last):
  File "/home/hari/sambashare/gyadav/MicrowaveProject_3rdApr2024/FIREANN_1/lammps_REANN/density.py", line 62, in forward
        angular=[f_cut.view(1,-1)]
        for ipsin in range(1,int(self.nipsin)):
            angular.append(torch.einsum("ji,ki -> jki",angular[-1],dist_vec).reshape(-1,totneighbour))
                           ~~~~~~~~~~~~ <--- HERE
        return torch.vstack(angular)

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.

#################################################################################################

Could you please advise on how I can resolve this issue? 


Thank you,
Gunjana

**Comment by zhangylch** [comment]
Sorry for the late reply. I am trying to reproduce the error.

**Comment by GunjanaYadav** [comment]
Hi,
I already solve the problem by modifying the file "lammps_REANN/density.py" a bit:

def angular(self,dist_vec,f_cut):

        # Tensor: dist_vec[neighbour*numatom*nbatch,3]
        # return: angular[neighbour*numatom*nbatch,npara[0]+npara[1]+...+npara[ipsin]]
        totneighbour=dist_vec.shape[0]
        dist_vec=dist_vec.permute(1,0).contiguous()

        f_cut = f_cut.to(dist_vec.device)  # Move f_cut tensor to the same device as dist_vec: gyadav

        angular=[f_cut.view(1,-1)]
        for ipsin in range(1,int(self.nipsin)):
            angular.append(torch.einsum("ji,ki -> jki",angular[-1],dist_vec).reshape(-1,totneighbour))
        return torch.vstack(angular)

Thanks

**Comment by zhangylch** [comment]
> Hi, I already solve the problem by modifying the file "lammps_REANN/density.py" a bit:
> 
> def angular(self,dist_vec,f_cut):
> 
> ```
>     # Tensor: dist_vec[neighbour*numatom*nbatch,3]
>     # return: angular[neighbour*numatom*nbatch,npara[0]+npara[1]+...+npara[ipsin]]
>     totneighbour=dist_vec.shape[0]
>     dist_vec=dist_vec.permute(1,0).contiguous()
> 
>     f_cut = f_cut.to(dist_vec.device)  # Move f_cut tensor to the same device as dist_vec: gyadav
> 
>     angular=[f_cut.view(1,-1)]
>     for ipsin in range(1,int(self.nipsin)):
>         angular.append(torch.einsum("ji,ki -> jki",angular[-1],dist_vec).reshape(-1,totneighbour))
>     return torch.vstack(angular)
> ```
> 
> Thanks

Good. But it is wired. f_cut is generated by dist_vec and the two tensors should be on the same device.
