### ISSUE TITLE
is there any example in non-uniform ﬁeld?

### ISSUE THREAD

**Issue by Eipgen** [zhangylch/FIREANN#7]
Hello, recently I read your perfect article and I saw that in the article you mentioned the work of **non-uniform electric fields**.
_" A feasible way is to discretize the non-uniform ﬁeld to each atomic center and introduce a nonequivalent ﬁeld-dependent function to each FI-EAD feature (as implicitly implied in Fig. 1) to approximate the response of each atomic density to the local ﬁeld experienced by the central atom."_
is there any example about this?

**Comment by zhangylch** [comment]
> Hello, recently I read your perfect article and I saw that in the article you mentioned the work of **non-uniform electric fields**. _" A feasible way is to discretize the non-uniform ﬁeld to each atomic center and introduce a nonequivalent ﬁeld-dependent function to each FI-EAD feature (as implicitly implied in Fig. 1) to approximate the response of each atomic density to the local ﬁeld experienced by the central atom."_ is there any example about this?

Sorry, it's not released yet. But it should be very simple. You can implement it yourself, using different field vectors at each atom center.

**Comment by Eipgen** [comment]
thank you very much, i will try it by myself
