### ISSUE TITLE
Clarification on Dipole Moment and Polarizability Tensor Calculation

### ISSUE THREAD

**Issue by GunjanaYadav** [zhangylch/FIREANN#8]
Hello,

I have a few questions regarding the calculation of the dipole moment and polarizability tensor for anisotropic media, as you mentioned these properties were part of your training data. Specifically:

1. Calculation of Properties: Could you please elaborate on how the dipole moment and polarizability tensor were calculated in your work? In your FIREANN research paper, you mentioned using DFT methods. Could you clarify which software package was used for these DFT calculations? I am considering using VASP, but I'm aware that calculating the polarizability tensor directly with VASP can be challenging. Any insights or suggestions would be greatly appreciated.

Example Software and Input Files: If possible, could you also share the name of the software and the corresponding input files you used to calculate these properties? This would be extremely helpful for me as I aim to apply your code, especially in the presence of an externally applied electric field.

2. Refitting Models: Lastly, is it possible to refit a model from a previously fitted one using your code? If so, could you provide some guidance on this process?

Thank you for your time and assistance!

Best regards,
Gunjana Yadav

**Comment by zhangylch** [comment]
> Hello,
> 
> I have a few questions regarding the calculation of the dipole moment and polarizability tensor for anisotropic media, as you mentioned these properties were part of your training data. Specifically:
> 
> 1. Calculation of Properties: Could you please elaborate on how the dipole moment and polarizability tensor were calculated in your work? In your FIREANN research paper, you mentioned using DFT methods. Could you clarify which software package was used for these DFT calculations? I am considering using VASP, but I'm aware that calculating the polarizability tensor directly with VASP can be challenging. Any insights or suggestions would be greatly appreciated.
> 
> Example Software and Input Files: If possible, could you also share the name of the software and the corresponding input files you used to calculate these properties? This would be extremely helpful for me as I aim to apply your code, especially in the presence of an externally applied electric field.
> 
> 2. Refitting Models: Lastly, is it possible to refit a model from a previously fitted one using your code? If so, could you provide some guidance on this process?
> 
> Thank you for your time and assistance!
> 
> Best regards, Gunjana Yadav

The dipole and polarizability calculations are gradients of the energy with respect to the electric field and are almost identical to the force calculations given in https://github.com/zhangylch/FIREANN/blob/main/pes/example/test.py.

The ab initio calculations are based on the cp2k and gaussian mentioned in our paper, and the input files have been given in the link to the FIREANN paper

Our model can be refitted from the provided model, see the manual for details. This is very simple, please read the manual in detail.

Best,
Yaolong

**Comment by GunjanaYadav** [comment]
Hi, 
when i am calculating the force using the test.py script, this error apperars:
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[4], line 1
----> 1 force=calculator.get_force(disp_cell,bcell,bcart,bef,index_cell,neigh_list,shifts,bspecies.view(-1))

File ~/sambashare/gyadav/fireann_18Sep2024/FIREANN/pes/new_example/calculate.py:23, in Calculator.get_force(self, disp_cell, cell, cart, ef, index_cell, neigh_list, shifts, species, create_graph)
     22 def get_force(self,disp_cell,cell,cart,ef,index_cell,neigh_list,shifts,species,create_graph=False):
---> 23     atomic_energy=self.pes(disp_cell,cell,cart,ef,index_cell,neigh_list,shifts,species)
     24     varene=torch.sum(atomic_energy)
     25     force=torch.autograd.grad(varene,cart,create_graph=create_graph)[0]

File ~/anaconda3/envs/fireann_18Sep2024/lib/python3.10/site-packages/torch/nn/modules/module.py:1501, in Module._call_impl(self, *args, **kwargs)
   1496 # If we don't have any hooks, we want to skip the rest of the logic in
   1497 # this function, and just call forward.
   1498 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1499         or _global_backward_pre_hooks or _global_backward_hooks
   1500         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1501     return forward_call(*args, **kwargs)
   1502 # Do not call functions when jit is used
   1503 full_backward_hooks, non_full_backward_hooks = [], []

RuntimeError: forward() expected at most 8 argument(s) but received 9 argument(s). Declaration: forward(__torch__.pes.PES.___torch_mangle_0.PES self, Tensor cell, Tensor cart, Tensor ef, Tensor index_cell, Tensor neigh_list, Tensor shifts, Tensor species) -> Tensor

**Comment by zhangylch** [comment]
> ## Hi,
> when i am calculating the force using the test.py script, this error apperars:
> RuntimeError Traceback (most recent call last) Cell In[4], line 1 ----> 1 force=calculator.get_force(disp_cell,bcell,bcart,bef,index_cell,neigh_list,shifts,bspecies.view(-1))
> 
> File ~/sambashare/gyadav/fireann_18Sep2024/FIREANN/pes/new_example/calculate.py:23, in Calculator.get_force(self, disp_cell, cell, cart, ef, index_cell, neigh_list, shifts, species, create_graph) 22 def get_force(self,disp_cell,cell,cart,ef,index_cell,neigh_list,shifts,species,create_graph=False): ---> 23 atomic_energy=self.pes(disp_cell,cell,cart,ef,index_cell,neigh_list,shifts,species) 24 varene=torch.sum(atomic_energy) 25 force=torch.autograd.grad(varene,cart,create_graph=create_graph)[0]
> 
> File ~/anaconda3/envs/fireann_18Sep2024/lib/python3.10/site-packages/torch/nn/modules/module.py:1501, in Module._call_impl(self, *args, **kwargs) 1496 # If we don't have any hooks, we want to skip the rest of the logic in 1497 # this function, and just call forward. 1498 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks 1499 or _global_backward_pre_hooks or _global_backward_hooks 1500 or _global_forward_hooks or _global_forward_pre_hooks): -> 1501 return forward_call(*args, **kwargs) 1502 # Do not call functions when jit is used 1503 full_backward_hooks, non_full_backward_hooks = [], []
> 
> RuntimeError: forward() expected at most 8 argument(s) but received 9 argument(s). Declaration: forward(**torch**.pes.PES.___torch_mangle_0.PES self, Tensor cell, Tensor cart, Tensor ef, Tensor index_cell, Tensor neigh_list, Tensor shifts, Tensor species) -> Tensor

Very sorry for the late reply. The script does have some bugs. I have fixed them and pushed them to the main branch. Please re-download and try again.

Best,
Yaolong
